[tool.black]
line_length = 100
include = '(snowflake_ext/.*\.py$|tests/.*\.py$)'
extend_exclude = '(.venv)'

[tool.isort]
profile = 'black'
line_length = 100

[tool.flake8]
max-line-length = 100
ignore = 'W503,E501'
exclude = '.venv*,dist,venv,build,.eggs'
